### ISSUE TITLE
POST of empty resource without ID attribute not supported

### ISSUE THREAD

**Issue by pencil** [ninech/REST-in-Peace#14]
``` ruby
class Resource
  include RESTinPeace

  rest_in_peace do
    use_api ->() { Faraday.new(url: 'http://rip.dev') }

    resource do
      post :create, '/rip'
    end

    attributes do
      read :ticket
    end
  end
end

Resource.new.create
```

=>

```
rest_in_peace.rb:18:in `hash_for_updates': undefined local variable or method `id' for #<Resource:0x007fbd6c2b2c18> (NameError)
        from rest-in-peace-2.0.1/lib/rest_in_peace/definition_proxy/resource_method_definitions.rb:27:in `block in post'
        from test.rb:23:in `<main>'
```

**Comment by luxflux** [comment]
Thanks a lot for pointing this out. I mentioned in the documentation that `id` is needed now. :beers:
